title: 2024 NSF SaTC Aspiring PI Workshop
subtitle: Research and Education Day
icon: /imgs/favicon.svg
contact: blase@uchicago.edu
deadline: March 13th, 2024
disabled_qualtrics: https://uchicago.co1.qualtrics.com/jfe/form/SV_6PZRP8m1VVaWbjw
#author:
#  name:
#  email: aaviv@gwu.ed
description: > # this means to ignore newlines until "show_excerpts:"
  The 2024 NSF SaTC Aspiring PI Workshop is designed to
  bring together researchers who aspiring to submit funded 
  Secure and Trustworthy Cyberspace (SaTC) proposals to the NSF. 
  The two day event, organized by a team from UChicago, UIC, and Purdue, 
  will provide aspiring 
  PIs an opportunity to workshop their grant writing skills with 
  mentorship from current PIs and NSF program officers.

show_excerpts: false # set to true to show excerpts on the homepage
future: true

privpol: https://privacy.uchicago.edu/privacy-policy/

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
#  social_links:
#    twitter: jekyllrb
#    github:  jekyll
# devto: jekyll
# dribbble: jekyll
# facebook: jekyll
# flickr:   jekyll
# instagram: jekyll
# linkedin: jekyll
# pinterest: jekyll
# youtube: jekyll
# youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
# youtube_channel_name: CloudCannon
# telegram: jekyll
# googleplus: +jekyll
# microdotblog: jekyll
# keybase: jekyll
# google_scholar_id: qc6CJjYAAAAJ

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

# GitLab instances
# gitlab:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up

header_pages:
  - panels.md
  - schedule.md
  - travel.md
  - mentors.md

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
